server {
    listen 80;
    server_name ВАШ_ДОМЕН.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ВАШ_ДОМЕН.com;

    ssl_certificate     /etc/letsencrypt/live/ВАШ_ДОМЕН.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ВАШ_ДОМЕН.com/privkey.pem;

    root /var/www/durak/frontend;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
